config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events

  root 'events#index'

  namespace :api, defaults: {format: :json} do 
    scope module: :v1 do
      resources :events, only: [:index, :show, :update, :create, :destroy]
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	DATE_MAPPING = {
		"Today" => :today, "All Dates" => :all, "Tomorrow" => :tomorrow, "This week" => :week
	}

  	geocoded_by :address
	after_validation :geocode, :if => :address_changed? 
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ActionController::Base
  before_filter :authenticate_user_from_token!
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
    render json: @events
  end

  def show
  	render json: @event
  end
  
  def create
    @event = Event.new(event_params)
      if @event.save
        render :show, status: :created, location: @event
      else
        render json: @event.errors, status: :unprocessable_entity
      end
  end

  def update
      if @event.update(event_params)
        render :show, status: :ok, location: @event
      else
        render json: @event.errors, status: :unprocessable_entity
      end
  end

  def destroy
    @event.destroy
    head :no_content
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :time, :host, :desc, :people, :price, :uid, :date, :adr, :event_url)
    end
  
    def authenticate_user_from_token!
      user_email = params[:user_email].presence
      user       = user_email && User.find_by_email(user_email)

      if user && Devise.secure_compare(user.authentication_token, params[:user_token])
        sign_in user, store: false
      end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    
    @q = Event.ransack(params[:q])
    @q.sorts = ['start_date asc'] if @q.sorts.empty?
    @events = Event.where("start_date >= ?", Time.zone.now.beginning_of_day)
    @events_by_day = @events.group_by { |t| t.start_date.beginning_of_day }
    @events = @q.result(distinct: true)

    @geektweet = twitter.search("to: meetgeekapp", result_type: "recent").take(3).collect do |tweet|
      "#{tweet.user.screen_name}: #{tweet.text}"
    end

  end

  def show
    @hash = Gmaps4rails.build_markers(@events) do |event, marker|
    marker.lat @event.latitude
    marker.lng @event.longitude
    end
    
    if params[:search].present?
    @events = Event.near(params[:search], 50, :order => :distance)
    else
    @events = Event.all
    end
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def twitter 
      $twitter = Twitter::REST::Client.new do |config|
        config.consumer_key = "LAc61L7oFsSxr45ilnpBikXhg"
        config.consumer_secret = 'hBQhwqTwfQNaz6484qNjTXYCQeQsq5A0MzhrOqs3oNkug4RuOz'
        config.access_token = '4857079966-J0WFLCgsAN9p6QxzXhwSMqLpmkneTkvIZpDcqAT'
        config.access_token_secret = 'mjgp5v3YspLxI5khSutASd39IWIROwODeBtj1hANaRSfw'
      end
    end

    def event_params
      params.require(:event).permit(:name, :time, :host, :desc, :people, :price, :uid, :start_date, :adr, :event_url, :latitude, :longitude, :address)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.text_field :time %>
  </div>
  <div class="field">
    <%= f.label :host %><br>
    <%= f.text_field :host %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :people %><br>
    <%= f.text_field :people %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :event_url %><br>
    <%= f.text_field :event_url %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date %>
  </div>
  <div class="field">
    <%= f.label :adr %><br>
    <%= f.text_field :adr %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<header id="top" class="header">
        <div class="text-vertical-center">
            <h1>Meet<b>Geek</h1>
</b>            <h3>All tech events in one place</h3>
            <br><br><br>
        </div>
    </header>

    <section class="col-lg-8 col-lg-offset-2 hidden-xs">
        <div class="filter-panel">
        <%= search_form_for @q do |f| %>
        <%= f.select :start_date, options_for_select([
      ['Today', Time.zone.today],
      ['Tomorrow', Time.zone.tomorrow],
      [(Time.zone.today + 2).strftime("%d %b"), Time.zone.today + 2],
      [(Time.zone.today + 3).strftime("%d %b"), Time.zone.today + 3],
      [(Time.zone.today + 4).strftime("%d %b"), Time.zone.today + 4],
      [(Time.zone.today + 5).strftime("%d %b"), Time.zone.today + 5],
      [(Time.zone.today + 6).strftime("%d %b"), Time.zone.today + 6]
    ]), include_blank: true %>
        <%= f.submit "Filtruj", class: %w{btn btn-default btn-sm} %>
        <% end %>
        </div>
    </section>

    <section id="about" class="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                </div>
            </div>
        </div>
    </section>
    
<% @events_by_day.each do |day, events| %>

<section class="black-content">
</section>
     
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
        <h2><b>
          <%= image_tag("calendarwhite.png", :alt => "calendar", :width => "30px", :height => "30px") %>
          <%= day.strftime("%A %d %B %Y") %>
        </b></h2>
    </div>
  </div>
</div> 

<div class="container">
  <div class="row col-md-10 col-md-offset-1">

    <% for event in events %>

      <div class="col-xs-12 col-sm-6 col-md-4 block-center">
        <div class="clear">
        </div>
        <div class="block">
          <div class="top-block">
            <div class="price">
              <div class="text-vertical-center"> 
  
                <% if (event.price == "0.00")%>
                    FREE
                  <% elsif (event.price == "") %>
                    FREE
                  <% elsif (event.price == "0.00 EUR") %>
                    FREE
                  <% elsif (event.price == "0.00 GBP") %>
                    FREE
                  <% else %>
                     <%= event.price %> 
                <% end %>

              </div>
            </div>
            <div class="title">
                <h3><b>
                  <%= truncate(event.name, length: 45, separator: ' ')%>
                </b></h3>
            </div>
          </div>
          <div class="down-block">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            <span class="glyphicon-class">Event start at: <%= event.time %></span><br>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <span class="glyphicon-class"> <%= truncate( event.adr, length:17, separator: ' ') %> </span>
          </div>
        </div>
      </div>

    <% end %>

  </div>
</div>
<% end %>


<div class="twitter-content">
  <div class="row">
    <div class="col-md-4 col-md-offset-4 text-center">
        <h2><b>
          <% @geektweet.each do |geektweet|%>
        
              <h3 style="color: #000"><%= geektweet %></h3>

          <% end %>
         
        </b></h2>
    </div>
  </div>
</div> 

<section class="col-xs-8 col-xs-offset-2">
  <div class="show-more-block">
    <div class="show-more-botton">
      <h3><b>
      Show more events
      </b></h3>
    </div>
  </div>
</section>
      
<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Meet<b>Geek</b></a>
    </div>
    <div class="collapse navbar-collapse">
     
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="search for event">
        </div>
        
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">About</a></li>
       <li><a href="#">Contact</a></li>
        </li>
      </ul>
    </div>
  </div>
</nav>

<header id="top" class="header">
  <div class="text-vertical-center">
    <h2>
      <%= @event.name %>
    </h2>
    <br><br><br>
  </div>
</header>

<section class="col-lg-8 col-lg-offset-2">
  <div class="top-card">
    <div class="register-botton">
      <h4><b>
      REGISTER
      </b></h4>
    </div>
    <div class="see-website">
      <h4><b>
      see event website
      </b></h4>
    </div>
    <div class="price-info">
      <h4><b>
      FREE
      </b></h4>
    </div>
  </div>
  <div class="down-card">
    <div class="info-card">    
      <h4><b><%= image_tag("calendar.png", :alt => "calendar", :width => "30px", :height => "30px") %> &nbsp
      <%= @event.start_date%> &nbsp &nbsp
      <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
      <span class="glyphicon-class"> <%= @event.adr %> </span> &nbsp &nbsp 
      <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
      <span class="glyphicon-class"><%= @event.time %></span><br></b></h4>&nbsp &nbsp
    </div>
    <div class="description">
      <p>
      <%= truncate( @event.desc, length:500, separator: ' ') %>
      </p>
    </div>
    <div style="border-top:2px solid grey; margin: 35px 20px;padding: 20px 0;">

    </div>
  </div>

  <div class="map">
    <div id="map" style='width: 800px; height: 400px;'>

    <script type="text/javascript">
      handler = Gmaps.build('Google');
handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
    {
      "lat": "<%= @event.latitude %>",
      "lng": "<%= @event.longitude %>",
      "picture": {
        "url": "http://maps.gstatic.com/mapfiles/markers2/marker.png",
        "width":  32,
        "height": 32
      },
      "infowindow": "<%= @event.adr %>"
    }
  ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  handler.getMap().setZoom(12);
});

</script>
    </div>
  </div>

<h3>You may also like</h3>
<ul>
<% for event in @event.nearbys(1) %>
  <div class="col-xs-12 col-sm-6 col-md-4 block-center">
        <div class="clear">
        </div>
        <div class="block">
          <div class="top-block">
            <div class="price">
              <div class="text-vertical-center"> 
  
                <% if (event.price == "0.00")%>
                    FREE
                  <% elsif (event.price == "") %>
                    FREE
                  <% elsif (event.price == "0.00 EUR") %>
                    FREE
                  <% elsif (event.price == "0.00 GBP") %>
                    FREE
                  <% else %>
                     <%= event.price %> 
                <% end %>

              </div>
            </div>
            <div class="title">
                <h3><b>
                  <%= truncate(event.name, length: 45, separator: ' ')%>
                </b></h3>
            </div>
          </div>
          <div class="down-block">
            <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
            <span class="glyphicon-class">Event start at: <%= event.time %></span><br>
            <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
            <span class="glyphicon-class"> <%= truncate( event.adr, length:17, separator: ' ') %> </span>
          </div>
        </div>
      </div>
<% end %>
</ul>

</section>

<

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>


<!-- .to_datetime.strftime("%d.%m.%Y" -->